#!/bin/sh
VERSION="1.1.4"

docker pull golang:1.5.2-alpine
mkdir go
git clone https://github.com/kubernetes/kubernetes.git "$PWD"/go/src/github.com/kubernetes/kubernetes
docker run -it --rm -v "$PWD"/go:/go -v "$PWD"/godepbuild:/godepbuild golang:1.5.2-alpine /godepbuild $VERSION
docker build -t asdfsx/docker-mesos-k8s:$VERSION .
